"use client";

import Link from "next/link";
import { EyeIcon, DownloadIcon, TrashIcon, ChevronLeftIcon, ChevronRightIcon, ChevronDownIcon } from "@/components/icons";
import type { FileType, ReportHistoryEntry } from "@/lib/dummy-data/reports";

const FILE_TYPE_STYLES: Record<FileType, string> = {
  PDF: "bg-red-100 text-red-600",
  Excel: "bg-forest-100 text-forest-700",
  CSV: "bg-sky-100 text-sky-700",
};

const PAGE_SIZES = ["5 / page", "10 / page", "25 / page"];
const TOTAL_RECORDS = 15;

export function ReportHistoryTable({
  entries,
  onDownload,
}: {
  entries: ReportHistoryEntry[];
  onDownload: (entry: ReportHistoryEntry) => void;
}) {
  return (
    <div className="rounded-xl border border-black/10 bg-white p-5">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="text-base font-semibold text-zinc-900">Report History</h2>
        <Link href="#" className="text-xs font-medium text-forest-700 hover:text-forest-800">
          View all history &rarr;
        </Link>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[880px] text-left text-sm">
          <thead>
            <tr className="border-b border-black/10 text-xs text-zinc-500">
              <th className="py-2 pr-3 font-medium">Report Name</th>
              <th className="py-2 pr-3 font-medium">Parameters</th>
              <th className="py-2 pr-3 font-medium">Generated By</th>
              <th className="py-2 pr-3 font-medium">Generated On</th>
              <th className="py-2 pr-3 font-medium">File Type</th>
              <th className="py-2 pr-3 font-medium">Records</th>
              <th className="py-2 pr-0 font-medium">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-black/5">
            {entries.map((entry) => (
              <tr key={entry.id} className="hover:bg-sage-50">
                <td className="py-2.5 pr-3 whitespace-nowrap font-medium text-zinc-900">{entry.reportName}</td>
                <td className="py-2.5 pr-3 whitespace-nowrap text-zinc-600">{entry.parameters}</td>
                <td className="py-2.5 pr-3 whitespace-nowrap text-zinc-600">{entry.generatedBy}</td>
                <td className="py-2.5 pr-3 whitespace-nowrap text-zinc-500">{entry.generatedOn}</td>
                <td className="py-2.5 pr-3">
                  <span className={`rounded-full px-2.5 py-1 text-[11px] font-medium whitespace-nowrap ${FILE_TYPE_STYLES[entry.fileType]}`}>
                    {entry.fileType}
                  </span>
                </td>
                <td className="py-2.5 pr-3 whitespace-nowrap text-zinc-600">{entry.records.toLocaleString()}</td>
                <td className="py-2.5 pr-0">
                  <div className="flex items-center gap-1">
                    <button
                      type="button"
                      aria-label="Preview report"
                      className="flex h-7 w-7 items-center justify-center rounded-md border border-black/10 text-zinc-500 hover:bg-sage-100"
                    >
                      <EyeIcon className="h-3.5 w-3.5" />
                    </button>
                    <button
                      type="button"
                      aria-label="Download report"
                      onClick={() => onDownload(entry)}
                      className="flex h-7 w-7 items-center justify-center rounded-md border border-black/10 text-zinc-500 hover:bg-sage-100"
                    >
                      <DownloadIcon className="h-3.5 w-3.5" />
                    </button>
                    <button
                      type="button"
                      aria-label="Delete report"
                      className="flex h-7 w-7 items-center justify-center rounded-md border border-red-200 text-red-500 hover:bg-red-50"
                    >
                      <TrashIcon className="h-3.5 w-3.5" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-black/10 pt-4 text-xs text-zinc-500">
        <p>
          Showing 1 to {entries.length} of {TOTAL_RECORDS} records
        </p>
        <div className="flex items-center gap-1">
          <button
            type="button"
            aria-label="Previous page"
            className="flex h-7 w-7 items-center justify-center rounded-md text-zinc-400 hover:bg-sage-100"
          >
            <ChevronLeftIcon className="h-3.5 w-3.5" />
          </button>
          {[1, 2, 3].map((page) => (
            <button
              key={page}
              type="button"
              className={`flex h-7 w-7 items-center justify-center rounded-md font-medium ${
                page === 1 ? "border border-forest-700 text-forest-700" : "text-zinc-600 hover:bg-sage-100"
              }`}
            >
              {page}
            </button>
          ))}
          <button
            type="button"
            aria-label="Next page"
            className="flex h-7 w-7 items-center justify-center rounded-md text-zinc-400 hover:bg-sage-100"
          >
            <ChevronRightIcon className="h-3.5 w-3.5" />
          </button>
        </div>
        <div className="relative">
          <select
            defaultValue={PAGE_SIZES[0]}
            className="appearance-none rounded-md border border-black/15 bg-white py-1 pl-2.5 pr-7 text-xs text-zinc-700 focus:border-forest-700 focus:outline-none"
          >
            {PAGE_SIZES.map((size) => (
              <option key={size}>{size}</option>
            ))}
          </select>
          <ChevronDownIcon className="pointer-events-none absolute right-1.5 top-1/2 h-3 w-3 -translate-y-1/2 text-zinc-400" />
        </div>
      </div>
    </div>
  );
}
