/** Read-only report generation history, sourced from the audit log. */

import Link from "next/link";
import { ChevronLeftIcon, ChevronRightIcon, ClipboardIcon } from "@/components/icons";
import { describeReportParameters, formatReportTimestamp } from "@/features/reports/history";
import { reportHistoryHref } from "@/features/reports/query";
import {
  REPORT_HISTORY_PAGE_SIZES,
  type ReportDefinition,
  type ReportFormat,
  type ReportHistoryPage,
  type ReportHistoryQuery,
} from "@/features/reports/types";

const FORMAT_STYLES: Record<ReportFormat, string> = {
  PDF: "bg-red-100 text-red-600",
  DOCX: "bg-sky-100 text-sky-700",
  CSV: "bg-forest-100 text-forest-700",
};
const FORMAT_NAMES: Record<ReportFormat, string> = { PDF: "PDF", DOCX: "Word", CSV: "CSV" };

const selectClasses =
  "rounded-lg border border-black/15 bg-white px-2.5 py-1.5 text-xs text-zinc-700 focus:border-forest-700 focus:outline-none focus:ring-1 focus:ring-forest-700";

function paginationPages(current: number, last: number) {
  return [...new Set([1, current - 1, current, current + 1, last])]
    .filter((page) => page >= 1 && page <= last)
    .sort((a, b) => a - b);
}

export function ReportHistoryTable({
  history,
  query,
  reports,
  storageLabels,
  errorMessage,
}: {
  history: ReportHistoryPage | null;
  query: ReportHistoryQuery;
  reports: ReportDefinition[];
  storageLabels: ReadonlyMap<string, string>;
  errorMessage?: string;
}) {
  const lastPage = history ? Math.max(1, Math.ceil(history.total / history.limit)) : 1;
  const pages = paginationPages(history?.page ?? 1, lastPage);
  const filtered = Boolean(query.type || query.result);

  return (
    <section id="report-history" className="scroll-mt-4 rounded-xl border border-black/10 bg-white p-5">
      <div className="mb-4 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h2 className="text-base font-semibold text-zinc-900">Report History</h2>
          <p className="text-xs text-zinc-500">
            Every generation attempt, from the audit log. Files are not stored; export again for current data.
          </p>
        </div>
        <form action="/reports#report-history" method="get" className="flex flex-wrap items-center gap-2">
          <label className="sr-only" htmlFor="historyType">Report</label>
          <select id="historyType" name="historyType" defaultValue={query.type} className={selectClasses}>
            <option value="">All reports</option>
            {reports.map((report) => (
              <option key={report.type} value={report.type}>{report.title}</option>
            ))}
          </select>
          <label className="sr-only" htmlFor="historyResult">Result</label>
          <select id="historyResult" name="historyResult" defaultValue={query.result} className={selectClasses}>
            <option value="">All results</option>
            <option value="SUCCESS">Generated</option>
            <option value="FAILED">Failed</option>
          </select>
          <label className="sr-only" htmlFor="historyLimit">Rows per page</label>
          <select id="historyLimit" name="historyLimit" defaultValue={query.limit} className={selectClasses}>
            {REPORT_HISTORY_PAGE_SIZES.map((size) => (
              <option key={size} value={size}>{size} / page</option>
            ))}
          </select>
          <button type="submit" className="rounded-lg bg-forest-700 px-3 py-1.5 text-xs font-semibold text-white hover:bg-forest-800">
            Apply
          </button>
          {filtered && (
            <Link href="/reports#report-history" className="text-xs font-medium text-forest-700 hover:text-forest-800">
              Clear
            </Link>
          )}
        </form>
      </div>

      {errorMessage ? (
        <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">
          <p className="font-semibold">Report history could not be loaded.</p>
          <p className="mt-1 text-amber-900">{errorMessage}</p>
        </div>
      ) : history && history.items.length > 0 ? (
        <>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[880px] text-left text-sm">
              <thead>
                <tr className="border-b border-black/10 text-xs text-zinc-500">
                  <th className="py-2 pr-3 font-medium">Report Name</th>
                  <th className="py-2 pr-3 font-medium">Parameters</th>
                  <th className="py-2 pr-3 font-medium">Generated By</th>
                  <th className="py-2 pr-3 font-medium">Generated On</th>
                  <th className="py-2 pr-3 font-medium">File Type</th>
                  <th className="py-2 pr-3 text-right font-medium">Records</th>
                  <th className="py-2 font-medium">Result</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-black/5">
                {history.items.map((item) => (
                  <tr key={item.id} className="align-top hover:bg-sage-50">
                    <td className="py-2.5 pr-3 font-medium text-zinc-900">{item.title ?? "Unknown report"}</td>
                    <td className="max-w-xs py-2.5 pr-3 text-zinc-600">{describeReportParameters(item, storageLabels)}</td>
                    <td className="whitespace-nowrap py-2.5 pr-3 text-zinc-600">{item.generatedBy?.fullName ?? "Unknown"}</td>
                    <td className="whitespace-nowrap py-2.5 pr-3 text-zinc-500">{formatReportTimestamp(item.generatedAt)}</td>
                    <td className="py-2.5 pr-3">
                      {item.format ? (
                        <span className={`whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-medium ${FORMAT_STYLES[item.format]}`}>
                          {FORMAT_NAMES[item.format]}
                        </span>
                      ) : (
                        <span className="text-zinc-400">—</span>
                      )}
                    </td>
                    <td className="whitespace-nowrap py-2.5 pr-3 text-right text-zinc-600">
                      {/* The Consolidated report is summary tables only, so it has no detail rows. */}
                      {item.type === "CONSOLIDATED_OPERATIONS"
                        ? "Summary"
                        : item.rowCount === null
                          ? "—"
                          : item.rowCount.toLocaleString()}
                    </td>
                    <td className="py-2.5">
                      {item.result === "SUCCESS" ? (
                        <span className="whitespace-nowrap rounded-full bg-forest-100 px-2.5 py-1 text-[11px] font-semibold text-forest-700">
                          Generated
                        </span>
                      ) : (
                        <div className="max-w-56">
                          <span className="whitespace-nowrap rounded-full bg-red-100 px-2.5 py-1 text-[11px] font-semibold text-red-700">
                            {item.result === "DENIED" ? "Denied" : "Failed"}
                          </span>
                          {item.error && <p className="mt-1 text-xs text-red-700">{item.error}</p>}
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <nav
            aria-label="Report history pagination"
            className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-black/10 pt-4 text-xs text-zinc-500"
          >
            <p>
              Showing {(history.page - 1) * history.limit + 1}–{Math.min(history.page * history.limit, history.total)} of{" "}
              {history.total.toLocaleString()}
            </p>
            <div className="flex items-center gap-1">
              {history.page > 1 ? (
                <Link href={reportHistoryHref(query, history.page - 1)} aria-label="Previous page" className="flex h-8 w-8 items-center justify-center rounded-md text-zinc-600 hover:bg-sage-100">
                  <ChevronLeftIcon className="h-3.5 w-3.5" />
                </Link>
              ) : (
                <span className="flex h-8 w-8 items-center justify-center text-zinc-300"><ChevronLeftIcon className="h-3.5 w-3.5" /></span>
              )}
              {pages.map((page, index) => (
                <span key={page} className="contents">
                  {index > 0 && pages[index - 1] !== page - 1 && <span className="px-1 text-zinc-400">…</span>}
                  <Link
                    href={reportHistoryHref(query, page)}
                    aria-current={page === history.page ? "page" : undefined}
                    className={`flex h-8 min-w-8 items-center justify-center rounded-md px-2 font-medium ${
                      page === history.page ? "border border-forest-700 text-forest-700" : "text-zinc-600 hover:bg-sage-100"
                    }`}
                  >
                    {page}
                  </Link>
                </span>
              ))}
              {history.page < lastPage ? (
                <Link href={reportHistoryHref(query, history.page + 1)} aria-label="Next page" className="flex h-8 w-8 items-center justify-center rounded-md text-zinc-600 hover:bg-sage-100">
                  <ChevronRightIcon className="h-3.5 w-3.5" />
                </Link>
              ) : (
                <span className="flex h-8 w-8 items-center justify-center text-zinc-300"><ChevronRightIcon className="h-3.5 w-3.5" /></span>
              )}
            </div>
          </nav>
        </>
      ) : (
        <div className="rounded-lg border border-dashed border-black/15 px-4 py-10 text-center">
          <ClipboardIcon className="mx-auto h-8 w-8 text-zinc-300" />
          <p className="mt-3 text-sm font-medium text-zinc-800">
            {filtered ? "No reports match these filters." : "No reports have been generated yet."}
          </p>
          <p className="mt-1 text-xs text-zinc-500">Each export you make is recorded here.</p>
        </div>
      )}
    </section>
  );
}
